name: Mirror Chart
run-name: Mirror Chart ${{ inputs.from }} -> ${{ inputs.to }}

on:
  workflow_dispatch:
    inputs:
      from:
        type: string
        description: OCI chart to mirror (e.g. registry-1.docker.io/bitnamicharts/postgresql:18.11.3)
        required: true
      
      to:
        type: string
        description: Name and tag of the mirrored chart in this repo. This can include namespace components too. (e.g. namespace/nested/postgres:18.11.3)
        required: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Mirror
        env:
          fromImage: ${{ inputs.from }}
          toImage: ${{ inputs.to }}
        run: |-
          docker pull "$fromImage"
          docker tag "$fromImage" "ghcr.io/${GITHUB_REPOSITORY,,}/$toImage"
          docker push  "ghcr.io/${GITHUB_REPOSITORY,,}/$toImage"
