name: Mirror Chart
run-name: Mirror Chart ${{ inputs.from }} -> ${{ inputs.to }}

on:
  workflow_dispatch:
    inputs:
      from:
        type: string
        description: OCI chart to mirror (e.g. registry-1.docker.io/bitnamicharts/postgresql:18.11.3)
        required: true
      
      to:
        type: string
        description: Name and tag of the mirrored chart in this repo. This can include namespace components too. (e.g. namespace/nested/postgres:18.11.3)
        required: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
            
      - name: Mirror
        env:
          fromImage: ${{ inputs.from }}
          toImage: ${{ inputs.to }}
        run: |-
          alias skopeo='nix run --inputs-from github:LCOGT/devenv-k8s/v1 nixpkgs#skopeo --'
          echo "${{ secrets.GITHUB_TOKEN }}" | skopeo login --username "${{ github.actor }}" ghcr.io
          skopeo copy --all "docker://$fromImage" "docker://ghcr.io/${GITHUB_REPOSITORY,,}/$toImage"
